apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: app01-api
  description: API app01
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $openapi: https://api.apis.guru/v2/openapi.yaml