apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: app01-api
  description: API app01
  links:
    - url: https://petstore.swagger.io/
      title: API Petstore
      icon: docs
spec:
  type: openapi
  lifecycle: experimental
  owner: cloudops
  system: ejie-system1
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.17
      title: Pet API
      license:
        name: MIT
    servers:
      - url: https://petstore3.swagger.io/api/v3
    paths:
      /pet/findByStatus:
        get:
          tags:
            - pet
          summary: Finds Pets by status
          description: Multiple status values can be provided with comma separated strings
          operationId: findPetsByStatus
          parameters:
            - name: status
              in: query
              description: Status values that need to be considered for filter
              required: false
              explode: true
              schema:
                type: string
                enum:
                  - available
                  - pending
                  - sold
                default: available
          responses:
            '200':
              description: successful operation
              content:
                application/xml:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pet'
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pet'
            '400':
              description: Invalid status value
          security:
            - petstore_auth:
                - 'write:pets'
                - 'read:pets'
          
