apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app01-ui
  description: App01 UI
  tags:
    - javascript
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=yelb-ui,tier=frontend'
    'backstage.io/techdocs-ref': dir:.
  links:
    - url: https://yelb-ui.example.com
      title: 'Yelb UI Information'
      icon: locallibrary
spec:
  type: service
  lifecycle: experimental
  owner: cloudops
  system: ejie-system1
  #dependsOn: [Component:yelb-appserver]
