apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: admin1-cloudops
spec:
  profile:
    displayName: Admin1 Clodops
    email: admin1-cloudops@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [cloudops]